Framework Refactored and Redesigned
783967/SwagLabsAutomation pull request #1
Opened 2024-09-30 08:03 UTC by subhamayghosh

Framework Refactored and Redesigned. Kindly review.

2024-10-03 09:45 UTC, 783967 requested changes
Please address the PR comments

2024-10-03 09:45 UTC, 783967 commented on src/test/java/swaglabs/TestComponents/Listeners.java
> +		// TODO Auto-generated method stub
Please dont keep blank methods. Add some code / body to these methods

2024-10-03 09:45 UTC, 783967 commented on src/test/java/swaglabs/common/CommonMethods.java
> +
Please add Javadocs to all the methods

2024-10-03 09:45 UTC, 783967 commented on src/test/java/swaglabs/common/CommonMethods.java
> +
Please add loggers

2024-10-20 18:50 UTC, 783967 approved these changes
Approved

2024-10-20 18:50 UTC, vitapase22 approved these changes
Correct

2024-10-20 18:51 UTC, merged

2024-12-06 09:25 UTC, subhamayghosh commented on src/test/java/swaglabs/common/CommonMethods.java
> +	public <T extends WebElement> void addToCartAndVerifyItemAdded(T addToCartElement, T removeFromCartElement) {
Provide valid name of the method based on functionality you are performing. You are performing add to cart and then removing it but method name is saying addToCartAndVerifyItemAdded. It could be addAndRemoveFromCartAndVerify(). Or else add two method for addToCart and removeFromCart as private and then create another public method verifyCartCount and call both private method.

2024-12-06 09:25 UTC, subhamayghosh reviewed
Changes requested