Feature/gha poc
783967/SwagLabsAutomation pull request #3
Opened 2024-11-12 09:11 UTC by 783967

GHA Yml file addd

2024-11-12 09:53 UTC, subhamayghosh approved these changes
approved

2024-11-12 09:53 UTC, merged

2024-11-13 04:09 UTC, Priyanka2245968 requested changes
This is close to perfect! Please address the suggested inline change.

2024-11-13 04:09 UTC, Priyanka2245968 commented on src/test/java/swaglabs/tests/validateHomePageTest.java
> -import swaglabs.TestComponents.DriverFactory;
Please add more information here, and fix this typo.

2024-11-26 15:31 UTC, Priyanka2245968 requested changes
This is close to perfect! Please address the suggested inline change.

2024-11-26 15:31 UTC, Priyanka2245968 commented on src/test/java/swaglabs/tests/validateHomePageTest.java
> -import swaglabs.TestComponents.DriverFactory;
Please add more information here, and fix this typo.

2024-11-26 15:32 UTC, Priyanka2245968 requested changes
This is close to perfect! Please address the suggested inline change.

2024-11-26 15:32 UTC, Priyanka2245968 commented on src/test/java/swaglabs/tests/validateHomePageTest.java
> -import swaglabs.stepDefinitions.HomePageSteps;
Please add more information here, and fix this typo.

2024-11-26 15:46 UTC, Priyanka2245968 commented on src/main/java/swaglabs/steps/HomePageSteps.java
> +import swaglabs.components.BasePage;
abcd