Google coding style Violates
783967/SwagLabsAutomation pull request #4
Opened 2024-11-26 16:49 UTC by subhamayghosh

2024-11-27 04:00 UTC, Priyanka2245968 requested changes
This is close to perfect! Please address the suggested inline change.

2024-11-27 04:00 UTC, Priyanka2245968 commented on src/main/java/swaglabs/common/CommonMethods.java
>  	 */
Please add more information here, and fix this typo.

2024-11-27 04:03 UTC, Priyanka2245968 requested changes
This is close to perfect! Please address the suggested inline change.

2024-11-27 04:03 UTC, Priyanka2245968 commented on src/main/java/swaglabs/common/CommonMethods.java
> +	public static <T extends WebElement> void waitForElementContainText(T element, String text, Integer timeoutSeconds) {
Please add more information here, and fix this typo.

2024-11-27 04:05 UTC, Priyanka2245968 requested changes
This is close to perfect! Please address the suggested inline change.

2024-11-27 04:05 UTC, Priyanka2245968 commented on src/main/java/swaglabs/common/CommonMethods.java
> +	//Test2
Please add more information here, and fix this typo.

2024-11-27 15:57 UTC, Priyanka2245968 requested changes
This is close to perfect! Please address the suggested inline change.

2024-11-27 15:57 UTC, Priyanka2245968 commented on src/main/java/swaglabs/common/CommonMethods.java
> +		switch(input) {
Please add more information here, and fix this typo.

2024-11-28 15:24 UTC, 783967 requested changes
This is close to perfect! Please address the suggested inline change.

2024-11-28 15:24 UTC, 783967 commented on src/main/java/swaglabs/common/CommonMethods.java
> +		switch(input) {
please correct the typo

2024-11-29 10:39 UTC, 783967 requested changes
Few review comments

2024-11-29 10:39 UTC, 783967 commented on src/test/java/swaglabs/tests/validateHomePageTest.java
>  import swaglabs.components.DriverFactory;
Please add more information here, and fix this typo.

2024-11-29 10:39 UTC, 783967 commented on src/main/java/swaglabs/common/CommonMethods.java
Ensure the login button is visible.

2024-12-05 12:30 UTC, 783967 requested changes
Few review comments

2024-12-06 10:12 UTC, closed without merging

2025-01-14 10:48 UTC, 783967 requested changes
Few review comments: