added api script
783967/SwagLabsAutomation pull request #7
Opened 2024-11-29 05:36 UTC by subhamayghosh

Added API scripts

2024-12-03 05:09 UTC, 783967 commented on src/test/java/swaglabs/tests/validateApiScript.java
> +	@Test
Please add priority and description

2024-12-03 05:09 UTC, 783967 commented on src/test/java/swaglabs/tests/validateApiScript.java
> +		RestClient restClient = new RestClient();
Please declare the RestClient globally instead of repeating in every method

2024-12-03 05:10 UTC, 783967 commented on src/test/java/swaglabs/tests/validateApiScript.java
> +	@Test(priority = 1, description = "Validate Get Call")
Please add proper description that is more detailed and meaningful

2024-12-03 05:11 UTC, 783967 commented on src/main/java/swaglabs/common/RestClient.java
> +import io.restassured.specification.RequestSpecification;
Please remove unwanted imports.

2024-12-03 05:12 UTC, 783967 commented on src/main/java/swaglabs/common/RestClient.java
> +		CloseableHttpClient httpClient = HttpClients.custom().setDefaultRequestConfig(config).build();
httpClient is not used anywhere. Please remove unused lines of code.

2024-12-03 05:14 UTC, 783967 commented on src/main/java/swaglabs/common/RestClient.java
> +		RestAssured.baseURI = url;
These comments are unwanted as the comment is not adding any additional value. The code is self-evident and it reveals what is being done. The comment does not add any additional context or meaning. hence, these kind of comments are not needed.

2024-12-03 05:16 UTC, 783967 commented on src/main/java/swaglabs/common/RestClient.java
> +		Response response = RestAssured.given().when().get(serviceUrl).then().statusCode(200).extract().response();
statusCode(200) is redundant here. Only extracting the response is sufficient here as the status code is anyways validated in line no 49

2024-12-03 05:16 UTC, 783967 commented on src/main/java/swaglabs/common/RestClient.java
> +		System.out.println("Response Body -> " + responseBody);
Remove println statements. Use loggers instead.

2024-12-03 05:17 UTC, 783967 commented on src/main/java/swaglabs/common/RestClient.java
> +		JSONObject responseJson = new JSONObject(responseBody);
This JSONObject and the previous responseBody is not used anywhere. What is the need for having this JSONObject. Please remove it.

2024-12-03 05:19 UTC, 783967 commented on src/main/java/swaglabs/common/RestClient.java
> +	public void post(String url, String serviceUrl) {
Custom method names should not be the same as RestAssured method names. Provide more meaningful names for custom methods. Also, instead of multiple different methods of get(), post(), etc, have a single method with switch case to handle all the http verb types.

2024-12-03 05:20 UTC, 783967 commented on src/main/java/swaglabs/common/RestClient.java
> +		requestBody.put("job", "leader");
Please create a payload structure separately and use it.

2024-12-03 05:21 UTC, 783967 requested changes
Please address the PR review comments

2024-12-06 10:11 UTC, closed without merging

2024-12-06 10:11 UTC, subhamayghosh commented
close